// backend/config/studentRegistry.js
// Danh bạ Hồ sơ Học vụ Chuẩn hóa Sinh viên HUTECH (Single Source of Truth)

export const STUDENT_REGISTRY = Object.freeze({
  '2280602154': {
    studentCode: '2280602154',
    fullName: 'Cao Hữu Nhân',
    birthDate: '26/07/2003',
    gender: 'Nam',
    studentClass: '22DTHE4',
    faculty: 'Khoa Công Nghệ Thông Tin',
    major: 'Công nghệ thông tin',
    phone: '0377913722',
    idCard: '079203001234',
    idCardDate: '10/05/2021',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    permanentAddress: '180 Ung Văn Khiêm, Phường 25, Quận Bình Thạnh, TP. Hồ Chí Minh',
    status: 'ACTIVE',
    admissionYear: 2022,
    enrolledCredits: 15,
  },
  '2110001': {
    studentCode: '2110001',
    fullName: 'Nguyễn Văn An',
    birthDate: '15/03/2003',
    gender: 'Nam',
    studentClass: '21DTHE1',
    faculty: 'Khoa Công Nghệ Thông Tin',
    major: 'Công nghệ thông tin',
    phone: '0901234568',
    idCard: '079201001234',
    idCardDate: '12/04/2021',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    permanentAddress: '180 Điện Biên Phủ, Phường 25, Quận Bình Thạnh, TP. Hồ Chí Minh',
    status: 'ACTIVE',
    admissionYear: 2021,
    enrolledCredits: 18,
  },
  '2110002': {
    studentCode: '2110002',
    fullName: 'Trần Thị Bình',
    birthDate: '10/08/2003',
    gender: 'Nữ',
    studentClass: '21DDTE2',
    faculty: 'Khoa Điện - Điện tử',
    major: 'Kỹ thuật điện tử',
    phone: '0901234571',
    idCard: '079201002345',
    idCardDate: '20/05/2021',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    permanentAddress: '475 Điện Biên Phủ, Phường 25, Quận Bình Thạnh, TP. Hồ Chí Minh',
    status: 'DROPPED',
    admissionYear: 2021,
    enrolledCredits: 0,
  },
  '2110003': {
    studentCode: '2110003',
    fullName: 'Lê Hoàng Cường',
    birthDate: '20/11/2003',
    gender: 'Nam',
    studentClass: '21DDTE1',
    faculty: 'Khoa Điện - Điện tử',
    major: 'Kỹ thuật điện tử',
    phone: '0901234569',
    idCard: '079201003456',
    idCardDate: '15/06/2021',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    permanentAddress: '475A Điện Biên Phủ, Phường 25, Quận Bình Thạnh, TP. Hồ Chí Minh',
    status: 'ACTIVE',
    admissionYear: 2021,
    enrolledCredits: 16,
  },
  '2110004': {
    studentCode: '2110004',
    fullName: 'Phạm Văn Dũng',
    birthDate: '01/01/2003',
    gender: 'Nam',
    studentClass: '22DTHE2',
    faculty: 'Khoa Công Nghệ Thông Tin',
    major: 'Công nghệ thông tin',
    phone: '0901234572',
    idCard: '079201004567',
    idCardDate: '18/07/2021',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    permanentAddress: '31/36 Ung Văn Khiêm, Phường 25, Quận Bình Thạnh, TP. Hồ Chí Minh',
    status: 'SUSPENDED',
    admissionYear: 2022,
    enrolledCredits: 0,
  },
  '2110005': {
    studentCode: '2110005',
    fullName: 'Hoàng Thị Mai',
    birthDate: '05/09/2002',
    gender: 'Nữ',
    studentClass: '20DDTE1',
    faculty: 'Khoa Điện - Điện tử',
    major: 'Kỹ thuật điện tử',
    phone: '0901234570',
    idCard: '079200005678',
    idCardDate: '10/08/2020',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    permanentAddress: '10/80C Song Hành, Phường Tân Hưng Thuận, Quận 12, TP. Hồ Chí Minh',
    status: 'ACTIVE',
    admissionYear: 2020,
    enrolledCredits: 3,
  },
});

/**
 * Lấy hồ sơ học vụ đầy đủ của sinh viên theo MSSV kèm fallback linh hoạt
 */
export function getStudentFullProfile(studentCode, fallbackUser = null) {
  const code = String(studentCode || fallbackUser?.studentCode || fallbackUser?.code || '').trim();
  const base = STUDENT_REGISTRY[code] || {};

  return {
    studentCode: code || base.studentCode || '',
    fullName: fallbackUser?.fullName || fallbackUser?.name || base.fullName || 'Sinh viên',
    birthDate: fallbackUser?.birthDate || base.birthDate || '26/07/2003',
    gender: fallbackUser?.gender || base.gender || 'Nam',
    studentClass: fallbackUser?.studentClass || fallbackUser?.class || base.studentClass || '22DTHE4',
    faculty: fallbackUser?.faculty || fallbackUser?.department || base.faculty || 'Khoa Công Nghệ Thông Tin',
    major: fallbackUser?.major || base.major || 'Công nghệ thông tin',
    phone: fallbackUser?.phone || base.phone || '0377913722',
    idCard: fallbackUser?.idCard || fallbackUser?.idCardNumber || fallbackUser?.citizenId || base.idCard || '079203001234',
    idCardDate: fallbackUser?.idCardDate || fallbackUser?.issueDate || base.idCardDate || '10/05/2021',
    idCardPlace: fallbackUser?.idCardPlace || fallbackUser?.issuePlace || base.idCardPlace || 'Cục Cảnh sát QLHC về TTXH',
    permanentAddress: fallbackUser?.permanentAddress || fallbackUser?.address || base.permanentAddress || '180 Ung Văn Khiêm, Phường 25, Quận Bình Thạnh, TP. Hồ Chí Minh',
    status: fallbackUser?.status || base.status || 'ACTIVE',
    admissionYear: fallbackUser?.admissionYear || base.admissionYear || 2022,
    enrolledCredits: fallbackUser?.enrolledCredits ?? base.enrolledCredits ?? 15,
  };
}

export default { STUDENT_REGISTRY, getStudentFullProfile };
